/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HibernateTarea4;

import Fichero.NewHibernateUtil;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author diego
 */
public class HibernateTarea4 extends javax.swing.JFrame {

    /**
     * Creates new form HibernateTarea4
     */
    public HibernateTarea4() {
        initComponents();
        jTableTabla.setVisible(false);
        jTableTabla.getTableHeader().setVisible(false);
        //jTextFieldExcepciones.setVisible(false);
        jTextFieldExcepciones.setEnabled(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres cerrar la aplicación?",
                        "Confirmación de cierre", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (option == JOptionPane.YES_OPTION) {
                    System.exit(0);
                    dispose();
                }
            }
        });
    }

    // Consulta por Codigo
    private void runQueryCodigo() {
        try {
            ejecutaHQLQuery("SELECT m.codigo, m.nombre, p.nombre, m.precioActual, m.stock, "
                    + "m.descatalogado FROM Medicamento m INNER JOIN m.proveedor p where m.codigo ="
                    + "" + Integer.parseInt(jTextFieldCodigo.getText()));
        } catch (HibernateException he) {
            he.printStackTrace();
        }
    }

    // Consulta por Nombre
    public void runQueryNombre() {
        ejecutaHQLQuery("SELECT m.codigo, m.nombre, p.nombre, m.precioActual, m.stock, m.descatalogado "
                + "FROM Medicamento m "
                + "INNER JOIN m.proveedor p where m.nombre like '%" + jTextFieldNombre.getText() + "%'");
    }

    private void ejecutaHQLQuery(String hql) {

        try {
            Session session = NewHibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query consulta = session.createQuery(hql);
            List resultList = consulta.list();
            mostrarResultado(resultList);
            session.getTransaction().commit();
        } catch (HibernateException he) {
            JOptionPane.showMessageDialog(null, he.getMessage().toString());
        }
    }

    private void mostrarResultado(List resultList) {
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Código");
        tableHeaders.add("Medicamento");
        tableHeaders.add("Proveedor");
        tableHeaders.add("Precio Actual");
        tableHeaders.add("Stock");
        tableHeaders.add("Descatalogado");

        for (Object obj : resultList) {
            Object[] rowArray = (Object[]) obj;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(rowArray[0]);  // Código
            oneRow.add(rowArray[1]);  // Nombre del medicamento
            oneRow.add(rowArray[2]);  // Nombre del proveedor
            oneRow.add(rowArray[3]);  // Precio actual
            oneRow.add(rowArray[4]);  // Stock
            oneRow.add(rowArray[5]);  // Descatalogado
            tableData.add(oneRow);
        }

        jTableTabla.setModel(new DefaultTableModel(tableData, tableHeaders));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTiltulo = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabla = new javax.swing.JTable();
        jTextFieldExcepciones = new javax.swing.JTextField();
        jButtonCerrar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTiltulo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTiltulo.setText("Medicamentos");

        jLabelCodigo.setText("Codigo:");

        jLabelNombre.setText("Nombre:");

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuscar.setText("Buscar Medicamento");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTableTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Medicamento", "Proveedor", "Precio actual", "Stock", "Descatalogado"
            }
        ));
        jScrollPane1.setViewportView(jTableTabla);

        jButtonCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCerrar.setText("CERRAR");
        jButtonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabelTiltulo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodigo)
                                    .addComponent(jLabelNombre))
                                .addGap(26, 26, 26)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombre))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscar))
                            .addComponent(jTextFieldExcepciones))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCerrar)
                .addGap(278, 278, 278))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTiltulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodigo)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextFieldExcepciones, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonCerrar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        jTableTabla.setVisible(false);
        jTableTabla.getTableHeader().setVisible(false);

        if (jTextFieldCodigo.getText().equals("") && jTextFieldNombre.getText().equals("")) {
            mostrarTabla(false, true, "Debes introducir el código o, al menos, parte del nombre del medicamento");
        } else {
            if (!jTextFieldCodigo.getText().equals("")) {

                if (!jTextFieldCodigo.getText().matches("[0-9]+")) {
                    mostrarTabla(false, true, "Debres introducir un dígito numérico");
                } else {
                    runQueryCodigo();
                    if (jTableTabla.getRowCount() == 0) {
                        mostrarTabla(false, true, "NO HAY MEDICAMENTOS");
                    } else {
                        mostrarTabla(true, false, "");
                    }
                }
            }
            if (!jTextFieldNombre.getText().equals("")) {
                if (!jTextFieldNombre.getText().matches("[a-zA-Z]+")) {
                    mostrarTabla(false, true, "Debes introducir solo letras");
                } else {
                    runQueryNombre();
                    if (jTableTabla.getRowCount() == 0) {
                        mostrarTabla(false, true, "NO HAY MEDICAMENTOS");
                    } else {
                        mostrarTabla(true, false, "");
                    }
                }

            }
        }

    }

    private void mostrarTabla(Boolean tabla, Boolean mensaje, String error) {

        if (tabla) {
            jTableTabla.setVisible(true);
            jTableTabla.getTableHeader().setVisible(true);
        } else {
            jTableTabla.setVisible(false);
            jTableTabla.getTableHeader().setVisible(false);
        }

        if (mensaje) {
            jTextFieldExcepciones.setEnabled(true);
            jTextFieldExcepciones.setBackground(Color.red);
            jTextFieldExcepciones.setVisible(true);
        } else {
            jTextFieldExcepciones.setEnabled(false);
            jTextFieldExcepciones.setBackground(Color.LIGHT_GRAY);
            jTextFieldExcepciones.setVisible(false);
        }

        jTextFieldExcepciones.setText(error);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HibernateTarea4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HibernateTarea4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HibernateTarea4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HibernateTarea4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HibernateTarea4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTiltulo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabla;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldExcepciones;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
