package Modelo;
// Generated 13-ene-2024 11:27:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private Integer codigo;
     private Proveedor proveedor;
     private String nombre;
     private float precioActual;
     private int stock;
     private Boolean descatalogado;
     private Set ventas = new HashSet(0);
     private Set pedidos = new HashSet(0);

    public Medicamento() {
    }

	
    public Medicamento(Proveedor proveedor, String nombre, float precioActual, int stock) {
        this.proveedor = proveedor;
        this.nombre = nombre;
        this.precioActual = precioActual;
        this.stock = stock;
    }
    public Medicamento(Proveedor proveedor, String nombre, float precioActual, int stock, Boolean descatalogado, Set ventas, Set pedidos) {
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.precioActual = precioActual;
       this.stock = stock;
       this.descatalogado = descatalogado;
       this.ventas = ventas;
       this.pedidos = pedidos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getPrecioActual() {
        return this.precioActual;
    }
    
    public void setPrecioActual(float precioActual) {
        this.precioActual = precioActual;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Boolean getDescatalogado() {
        return this.descatalogado;
    }
    
    public void setDescatalogado(Boolean descatalogado) {
        this.descatalogado = descatalogado;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


