package Modelo;
// Generated 13-ene-2024 11:27:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer codigo;
     private Medicamento medicamento;
     private Proveedor proveedor;
     private Date fecha;
     private int cantidad;

    public Pedido() {
    }

    public Pedido(Medicamento medicamento, Proveedor proveedor, Date fecha, int cantidad) {
       this.medicamento = medicamento;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.cantidad = cantidad;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


