package Modelo;
// Generated 13-ene-2024 11:27:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer codigo;
     private Medicamento medicamento;
     private Date fecha;
     private int unidades;
     private float importeUnidad;
     private float importeTotal;

    public Venta() {
    }

    public Venta(Medicamento medicamento, Date fecha, int unidades, float importeUnidad, float importeTotal) {
       this.medicamento = medicamento;
       this.fecha = fecha;
       this.unidades = unidades;
       this.importeUnidad = importeUnidad;
       this.importeTotal = importeTotal;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(int unidades) {
        this.unidades = unidades;
    }
    public float getImporteUnidad() {
        return this.importeUnidad;
    }
    
    public void setImporteUnidad(float importeUnidad) {
        this.importeUnidad = importeUnidad;
    }
    public float getImporteTotal() {
        return this.importeTotal;
    }
    
    public void setImporteTotal(float importeTotal) {
        this.importeTotal = importeTotal;
    }




}


